version: '3.8'

services:
  user-server:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DB_HOST: postgreSQL
    networks:
      - ktrek

networks:
  ktrek:
    external: true
